### ISSUE TITLE
REF: Issue #9 - same issue in Transmission

### ISSUE THREAD

**Issue by lintegras** [ccf-2012/seedcross#27] opened 2023-09-02 21:21 UTC
REF https://github.com/ccf-2012/seedcross/issues/9

Issue started with recent Transmission update:
Transmission
4.0.4
24077e3511

Logs:
Migrations for 'background_task':
  /usr/local/lib/python3.11/site-packages/background_task/migrations/0003_auto_20230831_2309.py
    - Alter field id on completedtask
    - Alter field id on task
Migrations for 'crseed':
  crseed/migrations/0008_alter_processparam_max_size_difference.py
    - Alter field max_size_difference on processparam
Operations to perform:
  Apply all migrations: admin, auth, background_task, contenttypes, crseed, sessions
Running migrations:
  Applying background_task.0003_auto_20230831_2309... OK
  Applying crseed.0004_auto_20220419_1221... OK
  Applying crseed.0005_crosstorrent_fixed... OK
  Applying crseed.0006_auto_20220503_1727... OK
  Applying crseed.0007_auto_20220505_1133... OK
  Applying crseed.0008_alter_processparam_max_size_difference... OK
(crseed.tasks) Start a routine to cross seed.
Clear old tasks and start...
config not ready...
Performing system checks...
System check identified no issues (0 silenced).
August 31, 2023 - 23:10:25
Django version 3.2.13, using settings 'csui.settings'
Starting development server at http://0.0.0.0:8019/
Quit the server with CONTROL-C.
config not ready...
Clear old tasks and start...
Starting at:09/02/2023, 19:00:35
Clear old tasks and start...
Starting at:09/02/2023, 19:01:52
Clear old tasks and start...
Starting at:09/02/2023, 19:05:43
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents
    torList = dlclient.loadTorrents()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents
    st = self.mkSeedTor(trTor)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker
    trackerJson["announce"]).netloc.split('.')
    ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'Tracker' object is not subscriptable
Marking task proceed_cross_seed as failed
Starting at:09/02/2023, 19:32:04
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents
    torList = dlclient.loadTorrents()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents
    st = self.mkSeedTor(trTor)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker
    trackerJson["announce"]).netloc.split('.')
    ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'Tracker' object is not subscriptable
Marking task proceed_cross_seed as failed
Clear old tasks and start...
Starting at:09/02/2023, 19:36:20
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents
    torList = dlclient.loadTorrents()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents
    st = self.mkSeedTor(trTor)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker
    trackerJson["announce"]).netloc.split('.')
    ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'Tracker' object is not subscriptable
Marking task proceed_cross_seed as failed
Starting at:09/02/2023, 19:36:26
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents
    torList = dlclient.loadTorrents()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents
    st = self.mkSeedTor(trTor)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker
    trackerJson["announce"]).netloc.split('.')
    ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'Tracker' object is not subscriptable
Marking task proceed_cross_seed as failed
Clear old tasks and start...
Starting at:09/02/2023, 21:08:16
Rescheduling proceed_cross_seed
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/background_task/tasks.py", line 43, in bg_runner
    func(*args, **kwargs)
  File "/code/seedcross/crseed/tasks.py", line 83, in backgroundCrossSeedTask
    iterTorrents(dlclient, param, log)
  File "/code/seedcross/crseed/CrossSeedAutoDL.py", line 428, in iterTorrents
    torList = dlclient.loadTorrents()
              ^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 97, in loadTorrents
    st = self.mkSeedTor(trTor)
         ^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 69, in mkSeedTor
    tracker=self.abbrevTracker(trTor.trackers[0]),
            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/code/seedcross/crseed/torclient.py", line 78, in abbrevTracker
    trackerJson["announce"]).netloc.split('.')
    ~~~~~~~~~~~^^^^^^^^^^^^
TypeError: 'Tracker' object is not subscriptable
Marking task proceed_cross_seed as failed

**Comment by Horridge** [comment] 2023-09-06 08:56
Looks like a duplicate of #26

**Closed** 2023-09-07 13:41 UTC
